---
title: "Untitled"
output: html_document
date: "2026-03-03"
---

# validación cruzada dejando uno fuera para construir el modelo de RLM de la figura 14.12.

```{r setup, include=FALSE}
library(caret)
library(dplyr)

# Imprimir mensajes de advertencia a medida que ocurren
opt <- options(warn = 1)

# Cargar y filtrar los datos
datos <- mtcars |> filter(wt > 2 & wt < 5) |>
  mutate(across(c("cyl", "vs", "am", "gear", "carb"), as.factor))

# Ajustar y mostrar el modelo usando validación cruzada dejando uno fuera
set.seed(111)
fmla <- formula("hp ~ mpg + cyl + disp + drat + qsec + vs + am + gear + carb")
entrenamiento <- train(fmla, data = datos, method = "lm",
                       trControl = trainControl(method = "LOOCV"))
modelo <- entrenamiento[["finalModel"]]

# Mostrar la fórmula y las predicciones del modelo
cat("Modelo obtenido con regsubset():\n")
cat("--------------------------------\n")
print(fmla)

cat("\nPredicciones en cada pliegue:\n")
print(entrenamiento[["pred"]])

cat("\nError estimado para el modelo:\n")
print(entrenamiento[["results"]])
```

# validación cruzada dejando uno fuera para construir el modelo de RLM de la figura 14.15 con un predictor menos (carb).

```{r setup, include=FALSE}

# Ajustar y mostrar el modelo usando validación cruzada
# dejando uno fuera sin la variable "carb".
set.seed(111)
fmla <- formula("hp ~ mpg + cyl + disp + drat + qsec + vs + am + gear")
entrenamiento <- train(fmla, data = datos, method = "lm",
                       trControl = trainControl(method = "LOOCV"))
modelo <- entrenamiento[["finalModel"]]

# Mostrar la fórmula y las predicciones del modelo modificado
cat("\nModelo con un predictor menos:\n")
cat("--------------------------------\n")
print(fmla)
cat("\n")

cat("Predicciones en cada pliegue:\n")
print(entrenamiento[["pred"]])

# Mostrar el resultado estimado para el modelo
cat("\nError estimado para el modelo:\n")
print(entrenamiento[["results"]])

# Reestabler opción para warnings
options(warn = opt[[1]])

```
