---
title: "Untitled"
output: html_document
date: "2026-03-03"
---

# regresión lineal para predecir la potencia del motor (en vehículos entre 2 y 5 mil libras) a partir de dos predictores: el volumen útil de sus cilindros y el peso del vehículo.


```{r setup, include=FALSE}

library(dplyr)
library(scatterplot3d)

# Cargar y filtrar los datos
datos <- mtcars |> filter(wt > 2 & wt < 5)

# Ajustar y mostrar un modelo de LRM para la potencia del motor
modelo <- lm(hp ~ disp + wt, data = datos)
print(summary(modelo))

```

# gráfico 3D del plano de regresión obtenido para el ejemplo.

```{r setup, include=FALSE}

# Graficar el modelo ajustado, diferenciando valores sobre y bajo el plano
i_color <- 1 + (resid(modelo) > 0)
g <- scatterplot3d(
  datos[["disp"]], datos[["wt"]], datos[["hp"]], type = "p", angle = 50,
  pch = 16, color = c("steelblue1", "steelblue4")[i_color],
  xlab = bquote("Volumen útil de los cilindros" ~ group("[", "in"^3, "]")),
  ylab = "Peso [lb x 1000]\n\n\n",
  zlab = "Potencia [hp]",
  mar = c(3, 3, 1, 0) + 0.1
)
g$plane3d(modelo, draw_lines = TRUE, lty = "dotted")

```

# uso del modelo de RLM para predecir la potencias de otros vehículos.

```{r setup, include=FALSE}

# Definir valores de los predictores para vehículos no incluidos
# en el conjunto mtcars.
modelos <- c("Chevrolet Vega", "Ford Pinto", "AMC Pacer",
             "Plymouth Valiant Duster", "Chevrolet Impala Caprice")
disp <- c(140, 98, 232, 360, 350)
wt <- c(2.2, 2.0, 3.0, 3.5, 2.5)
datos_nuevos <- data.frame(disp, wt)
rownames(datos_nuevos) <- modelos

# Usar el modelo para predecir el rendimiento de otros modelos
hp_est <- predict(modelo, newdata = datos_nuevos)
datos_nuevos <- cbind(datos_nuevos, hp_est)

# Mostrar los resultados
cat("Predicciones:\n")
print(datos_nuevos)

```

