---
title: "Lectura 9 - Código 4"
output: html_document
date: "2026-03-03"
---

# Prueba de permutación para la diferencia de dos varianzas.

```{r setup, include=FALSE}

library(dplyr)
library(ggplot2)
library(glue)
library(purrr)
library(rsample)
library(tibble)
library(tidyr)

# Crear muestras iniciales
notas_I <- c(5.4, 4.7, 6.3, 2.9, 5.9, 5.1, 2.1, 6.2, 1.6, 6.7, 3.0, 3.3, 5.0, 4.1, 3.3, 3.4, 1.2, 3.8, 5.8, 4.2)
notas_U <- c(4.0, 4.1, 4.3, 4.3, 4.3, 4.2, 4.3, 4.3, 4.4, 4.1, 4.3, 4.0)

# Crear matriz de datos con las muestras independientes
Muestra <- factor(c(rep("I", length(notas_I)), rep("U", length(notas_U))))
datos_largos <- tibble(Muestra, Nota = c(notas_I, notas_U))

# Crear las muestras
R = 5999
set.seed(432)
remuestras <- permutations(datos_largos, permute = Nota, times = R, apparent = TRUE)

# Función que devuelve los estadísticos de interés para la diferencia de dos varianzas
# en una remuestra.
dif_dos_varianzas <- function(remuestra, ...) {
    analysis(remuestra) |> group_by(Muestra) |> summarise(v = var(Nota)) |> 
    summarise(v[1] - v[2]) |> pull()
}

# Obtener la distribución permutada de la diferencia de las medias
dist_perm <- remuestras |> mutate(dif_v = map(splits, dif_dos_varianzas)) |> unnest(dif_v)

```

# gráfica del contraste de las hipótesis de igualdad de las varianzas usando una prueba de permutación.

```{r, echo=FALSE}
# Obtener la diferencia de las varianzas observada en las muestras originales
dif_obs <- dist_perm |> filter(id == "Apparent") |> pull(dif_v)

# Calcular el valor p
n_extremos <- dist_perm |> filter(abs(dif_v) >= abs(dif_obs)) |> summarise(n = n())
p_valor <- n_extremos / (R + 1) # n_extremos ya incluye la diferencia observada

# Crear y mostrar situación de manera gráfica
titulo <- paste("Contraste de hipótesis usando", R, "permutaciones")
nota <- if_else(p_valor < 0.001, 
                glue("italic(p)", "< ", "'{sprintf('%3f', 0.001)}'"), 
                glue("italic(p)", "==", "'{sprintf('%3f', p_valor)}'"))

ancho_barra <- diff(range(dist_perm[["dif_v"]]) / nclass.scott(dist_perm[["dif_v"]]))
ancho_barra_ajustado <- abs(dif_obs) / max(1, round(abs(dif_obs) / ancho_barra))

dist_perm_pl <- dist_perm |> 
mutate(extremo = factor(if_else(abs(dif_v) >= abs(dif_obs), 1, 0))) |> 
ggplot(aes(x = dif_v)) +
geom_histogram(aes(alpha = extremo), boundary = 0, binwidth = ancho_barra_ajustado,
    color = "steelblue4", fill = "steelblue") +
labs(title = titulo, x = "Diferencia de dos varianzas", y = "Frecuencia") +
geom_vline(xintercept = c(-dif_obs,dif_obs), colour = "steelblue4", linetype = "dashed") +
annotate("text", x = dif_obs, y = Inf, hjust = 1.2, vjust = 2, label = nota, parse=TRUE) +
scale_alpha_manual(values = c("0" = 0.2, "1" = 1), guide = NULL) +
theme(plot.title = element_text(hjust = 0.5)) + theme_pubr()
```
