---
title: "Lectura 9 - Código 5"
output: html_document
date: "2026-03-03"
---
# Prueba de permutación para la diferencia de tres medias correlacionadas.
```{r setup, include=FALSE}

library(dplyr)
library(forcats)
library(ggpubr)
library(glue)
library(purrr)
library(rsample)
library(rstatix)
library(tibble)
library(tidyr)

# Crear la matriz de datos y llevarla a formato largo
Quicksort  <- c(11.2, 22.6, 23.4, 23.3, 21.8, 40.1)
Bubblesort <- c(10.7, 24.3, 25.7, 25.8, 24.8, 45.3)
Mergesort  <- c(10.0, 23.7, 23.7, 21.7, 23.5, 42.7)
Instancia  <- factor(paste0("I", 1:6))

datos_anchos <- tibble(Instancia, Quicksort, Bubblesort, Mergesort)
datos_largos <- datos_anchos |>
  pivot_longer(-Instancia, names_to = "Algoritmo", values_to = "Tiempo") |>
  mutate(Algoritmo = fct(Algoritmo))

# Reescribir la función que usa permutations() para crear las permutaciones
perm_splits_por_instancia <- function (data, times = 25) {
  n <- nrow(data)
  d1 <- data |> select(Instancia) |> mutate(fila = row_number())   # línea agregada
  # indices <- (rep(n, times), sample, replace = FALSE) # línea cambiada por:
  indices <- map(1:times, ~ {d1 |> slice_sample(by = Instancia, n = n) |> pull(fila)})
  indices <- lapply(indices, rsample:::perm_complement, n = n)
  split_objs <- map(indices, make_splits, data = data, class = "perm_split")
  list(splits = split_objs, id = rsample:::names0(length(split_objs), "Permutations"))
}
assignInNamespace("perm_splits", perm_splits_por_instancia, ns = "rsample")

# Crear las remuestras
R <- 2999
set.seed(432)
remuestras <- permutations(datos_largos, permute = Tiempo, times = R, apparent = TRUE)

# Función que devuelve el estadístico F para las medidas repetidas en una remuestra
calc_F <- function(remuestra, ...) {
  analysis(remuestra) |>
    anova_test(dv = Tiempo, wid = Instancia, within = Algoritmo, type = 1) |> as_tibble() |>
    pull(F)
}

# Obtener la distribución permutada de la diferencia de las medias
dist_perm <- remuestras |> mutate(F = map(splits, calc_F)) |> unnest(F)

```


# Gráfica del contraste de las hipótesis de igualdad de 3 medias correlacionadas usando una prueba de permutación.

```{r}

# Obtener el estadístico F observado en las muestras originales
F_obs <- dist_perm |> filter(id == "Apparent") |> pull(F)

# Calcular el valor p
n_extremos <- dist_perm |> filter(F >= F_obs) |> summarise(n = n())
p_valor <- n_extremos / (R + 1)

# Crear y mostrar la situación de manera gráfica
titulo <- sprintf("Contraste de hipótesis usando %d permutaciones", R)
nota <- if_else(p_valor < 0.001, glue("italic(p)", " < ", "'{sprintf('%.3f', 0.001)}'"),
                                 glue("italic(p)", " == ", "'{sprintf('%.3f', p_valor)}'"))

dist_perm_pl <- dist_perm |>
  mutate(extremo = factor(if_else(F >= F_obs, 1, 0))) |> ggplot(aes(x = F)) +
  geom_histogram(aes(alpha = extremo), boundary = F_obs,
                 binwidth = diff(range(dist_perm[["F"]])) / nclass.scott(dist_perm[["F"]]),
                 color = "steelblue4", fill = "steelblue") +
  labs(title = titulo, x = "F", y = "Frecuencia") +
  geom_vline(xintercept = F_obs, colour = "steelblue4", linetype = "dashed") +
  annotate("text", x = F_obs, y = Inf, hjust = 1.1, vjust = 2, label = nota, parse = TRUE) +
  scale_alpha_manual(values = c("0" = 0.2, "1" = 1), guide = NULL) +
  theme_pubr() + theme(plot.title = element_text(hjust = 0.5))

print(dist_perm_pl)
```


# análisis post-hoc para la prueba de permutación realizada.


```{r}
# Función que devuelve las medias de las diferencias de los tiempos de ejecución
# entre pares de algoritmos según una remuestra.
medias_dif_pares <- function(remuestra, ...) {
  d1 <- analysis(remuestra)
  d1 |> get_comparisons(Algoritmo) |> unname() |>
    map(~ {nombre <- paste(.x[1], .x[2], sep = " - ")
          d1 |>
            reframe(difs = Tiempo[Algoritmo == .x[1]] - Tiempo[Algoritmo == .x[2]]) |>
            summarise(!!nombre := mean(difs))}
    ) |> list_cbind()
}

# Obtener la distribución permutada de las medias de las diferencias de tiempo de
# ejecución entre pares de algoritmos.
posthoc_perm <- remuestras |> mutate(medias_dif = map(splits, medias_dif_pares)) |>
  unnest(medias_dif)

# Obtener las medias de las diferencias de tiempo de ejecución entre pares de algoritmos
# observadas en las muestras originales.
posthoc_medias_obs <- posthoc_perm |> filter(id == "Apparent") |> select(-splits, -id)

# Calcular el valor p para cada caso
n_extremos <- posthoc_perm |>
  summarise(across(.cols = where(is.numeric),
                   .fns = ~ sum(abs(.x) >= abs(posthoc_medias_obs[[cur_column()]]))))
p_valores <- n_extremos / (R + 1)

# Producir una tabla con las medias de las diferencias entre cada par de algoritmos
# observadas en las muestras originales.
posthoc_tbl <- bind_rows(posthoc_medias_obs, p_valores, .id = "est") |>
  mutate(est = c("Media dif. obs.", "p_perm")) |>
  pivot_longer(-est, names_to = "Par de algoritmos", values_to = "Valor") |>
  pivot_wider(names_from = est, values_from = Valor) |>
  adjust_pvalue(p.col = "p_perm", output.col = "p_perm_adj", method = "BH") |>
  mutate(across(where(is.numeric), ~ num(., digits = 3)))

# Mostrar los resultados del análisis post-hoc
msg <- "Resultados del análisis post-hoc"
cat(msg, ":\n", sep = "")
cat(rep("-", nchar(msg)), "\n", sep = "")
print(posthoc_tbl)
```
