---
title: "Lectura 6 - Procedimiento post-hoc de Scheffé usando ScheffeTest()"
output: html_document
date: "2025-09-15"
---



```{r}
library(DescTools)
library(tidyr)
library(dplyr)
library(ez)
library(ggpubr)

# Crear la matriz de datos en formato ancho
A <- c(23, 19, 25, 23, 20)
B <- c(26, 24, 28, 23, 29)
C <- c(19, 24, 20, 21, 17)
datos_anchos <- data.frame(A, B, C)

# Llevar la matriz a formato largo
datos_largos <- datos_anchos |>
  pivot_longer(c("A", "B", "C"), names_to = "Algoritmo", values_to = "Tiempo") |>
  mutate(Instancia = factor(1:n())) |>
  mutate(Algoritmo = factor(Algoritmo))

# Comprobar la condición de normalidad con gráficos Q-Q
g1 <- ggqqplot(datos_largos, x = "Tiempo", y = "Algoritmo", color = "Algoritmo", alpha = 0.7,
               palette = c("steelblue", "steelblue1", "steelblue4"))
g1 <- g1 + facet_wrap(~ Algoritmo)
g1 <- g1 + rremove("x.ticks") + rremove("x.text")
g1 <- g1 + rremove("y.ticks") + rremove("y.text")
g1 <- g1 + rremove("axis.title")
print(g1)
```


```{r}

# Realizar y mostrar el procedimiento ANOVA con aov()
prueba_aov <- aov(Tiempo ~ Algoritmo, data = datos_largos)
cat("Procedimiento ANOVA usando aov\n")
cat("---\n")
print(summary(prueba_aov))


```


```{r}
# Realizar y mostrar el procedimiento ANOVA con ezANOVA()
prueba_ez <- ezANOVA(data = datos_largos, dv = Tiempo, between = Algoritmo, 
                     wid = Instancia, return_aov = TRUE, detailed = TRUE)

cat("\nProcedimiento ANOVA usando ezANOVA\n")
cat("---\n")
print(prueba_ez)



```

```{r}

# Obtener, cambiar colores y mostrar el gráfico del tamaño del efecto
g2 <- ezPlot(data = datos_largos, dv = Tiempo, wid = Instancia, between = Algoritmo, 
             y_lab = "Tiempo promedio de ejecución [ms]", x = Algoritmo)
g2 <- g2 + theme_pubr()
g2[["layers"]][[1]][["aes_params"]] <- list(colour = "steelblue", alpha = 0.7) # puntos
g2[["layers"]][[2]][["aes_params"]] <- list(colour = "steelblue", alpha = 0.7) # líneas
g2[["layers"]][[3]][["aes_params"]] <- list(colour = "steelblue", alpha = 0.7) # error
print(g2)
```


```{r}
# Definir nivel de significación
alfa <- 0.025

# Realizar y mostrar un procedimiento post-hoc de Holm
holm <- pairwise.t.test(datos_largos[["Tiempo"]], datos_largos[["Algoritmo"]],
                        p.adjust.method = "holm", pool.sd = TRUE, paired = FALSE,
                        conf.level = 1 - alfa)
cat("\n\nProcedimiento post-hoc de Holm\n")
cat("---\n")
print(holm)

# Realizar y mostrar un procedimiento post-hoc de Benjamini y Hochberg
bh <- pairwise.t.test(datos_largos[["Tiempo"]], datos_largos[["Algoritmo"]],
                      p.adjust.method = "fdr", pool.sd = TRUE, paired = FALSE,
                      conf.level = 1 - alfa)
cat("\nProcedimiento post-hoc de Benjamini y Hochberg\n")
cat("---\n")
print(bh)

```

```{r}
# Realizar y mostrar procedimiento HSD de Tukey
hsd <- TukeyHSD(prueba_aov, "Algoritmo", ordered = TRUE, conf.level = 1 - alfa)
cat("\nProcedimiento HSD de Tukey\n")
cat("---\n")
print(hsd)

```



```{r }
# Crear matriz de contrastes para la prueba de Scheffé
contrastes <- matrix(c(1, -1, 0, 
                       1, 0, -1, 
                       0, 1, -1,
                       1, -0.5, -0.5, 
                       -0.5, 1, -0.5, 
                       -0.5, -0.5, 1),
                     ncol = 3, byrow = TRUE)

# Trasponer matriz de contrastes (para que cada contraste sea una columna)
contrastes <- t(contrastes)

# Realizar y mostrar un procedimiento post-hoc de Scheffé
scheffe <- ScheffeTest(x = prueba_aov, which = "Algoritmo",
                       contrasts = contrastes, conf.level = 1 - alfa)
cat("\nProcedimiento post-hoc de Scheffé\n")
cat("---\n")
print(scheffe)



```
